excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - iOS-Architecture-MVVMCTests
    - iOS-Architecture-MVVMCUITests
disabled_rules:
    - force_cast
    - force_unwrapping
line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - x
    - y
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - I
    - O
  allowed_symbols: ["_"] # these are allowed in type names
